before_script:
  - apt-get install -qq -y python3 python-pip
  - pip3 install -q err pytest pytest-pep8 requests coverage --use-wheel

errbot:
  script:
    - coverage run --source plugins -m py.test --pep8
