language: python
python:
  - 3.3
  - 3.4
  - 3.5
cache:
  - pip: true
install:
  - pip install -q errbot pytest requests --use-wheel
  - pip install -q coverage coveralls --use-wheel
script:
  - coverage run --source plugins -m py.test
notifications:
  email: false
after_success:
  coveralls
