language: python
python:
  - 3.3
  - 3.4
  - 3.5
cache:
  - pip: true
install:
  - pip install -q errbot pytest pytest-pep8 requests --use-wheel
  - pip install -q redis --use-wheel
  - pip install -q coverage coveralls --use-wheel
services:
  - redis-server
script:
  - coverage run --source plugins -m py.test --pep8
notifications:
  email: false
after_success:
  coveralls
